### 상품 서비스의 목록 호출
GET localhost:9000/api/products
Content-Type: application/json


### 주문 서비스의 목록 호출
GET localhost:9000/api/order
Content-Type: application/json


### 인벤토리 서비스의 목록 호출
GET localhost:9000/api/inventory
Content-Type: application/json